config/routes.rb
Easyeval::Application.routes.draw do
  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_messages.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert(class=(name == :notice ? "alert-success" : "alert-error"))
      a.close(data-dismiss="alert") &#215
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.slim
= link_to "EasyEval", root_path, :class => 'brand'
ul.nav
  - if user_signed_in?
    li= link_to 'Logout', destroy_user_session_path, :method=>'delete'
    li= link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      li= link_to 'Admin', users_path
  - else
    li= link_to 'Login', new_user_session_path

app/views/layouts/application.slim
doctype html
html
  head
    head
      meta(name="viewport" content="width=device-width, initial-scale=1.0")
      title= content_for?(:title) ? yield(:title) : "EasyEval"
      meta(name="description" content=(content_for?(:description) ? yield(:description) : "EasyEval"))
      = stylesheet_link_tag "application", :media => "all"
      = javascript_include_tag "application"
      = csrf_meta_tags
      = yield(:head)
  body(class="#{controller_name} #{action_name}")
    header(class="navbar navbar-fixed-top")
      nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main(role="main")
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          footer